namespace OpenSorSe.Desktop.ViewModels;

/// <summary>Identifies one centrally maintained internal Help topic.</summary>
public enum HelpTopicId
{
    /// <summary>General Help overview.</summary>
    HelpOverview,
    /// <summary>Dashboard guidance.</summary>
    Dashboard,
    /// <summary>Folder selection and scan guidance.</summary>
    ScanFolders,
    /// <summary>Results exploration guidance.</summary>
    Results,
    /// <summary>Change Plan review, validation, apply, and Undo guidance.</summary>
    ReviewChanges,
    /// <summary>Grouped duplicate-review guidance.</summary>
    DuplicateView,
    /// <summary>Saved-catalog guidance.</summary>
    SavedCatalog,
    /// <summary>Catalog metadata-search guidance.</summary>
    CatalogSearch,
    /// <summary>Historical comparison guidance.</summary>
    CompareSnapshots,
    /// <summary>Local Search and background-indexing guidance.</summary>
    SemanticSearch,
    /// <summary>Folder restructuring history and diagram guidance.</summary>
    StructureHistory,
    /// <summary>Deterministic rule guidance.</summary>
    Rules,
    /// <summary>Settings guidance.</summary>
    Settings,
    /// <summary>Application diagnostics guidance.</summary>
    Diagnostics,
    /// <summary>Operation-history guidance.</summary>
    OperationHistory,
    /// <summary>Optional Ollama setup guidance.</summary>
    AiSetup,
    /// <summary>Review-only AI suggestion guidance.</summary>
    AiSuggestions,
    /// <summary>Persistent watched-folder guidance.</summary>
    WatchedFolders,
    /// <summary>Reusable workflow-profile guidance.</summary>
    Workflows,
    /// <summary>Evidence-backed Related Files guidance.</summary>
    RelatedFiles,
    /// <summary>Local index and optional-AI privacy guidance.</summary>
    Privacy,
    /// <summary>Bounded image, audio, and video indexing guidance.</summary>
    MediaIntelligence,
    /// <summary>Common recovery and troubleshooting guidance.</summary>
    Troubleshooting,
    /// <summary>Advanced-interface guidance.</summary>
    AdvancedFeatures,
    /// <summary>Product identity guidance.</summary>
    About,
}

/// <summary>Contains structured, maintainable content for one internal Help topic.</summary>
public sealed record HelpTopic(
    HelpTopicId Id,
    string Title,
    string Purpose,
    string Reads,
    string Changes,
    string DoesNotChange,
    IReadOnlyList<string> Workflow,
    IReadOnlyList<string> ImportantControls,
    string EmptyStates,
    string CommonErrors,
    string SafetyNotes,
    IReadOnlyList<HelpTopicId> RelatedTopics);

/// <summary>Owns the complete bounded built-in Help catalog.</summary>
public static class HelpCatalog
{
    private static readonly IReadOnlyList<HelpTopic> TopicsValue = Array.AsReadOnly(
    [
        Topic(HelpTopicId.HelpOverview, "Getting Started", "Choose a task or page to understand what OpenSorSe reads, stores, and can change.",
            "Only this built-in help catalog.", "Only the selected Help topic.",
            "Files, settings, snapshots, tags, and saved searches.",
            ["Choose a topic.", "Read its workflow and safety notes.", "Use Back to previous page when available."],
            ["Topic list", "Back to previous page"], "Select a topic when no details are shown.",
            "Unknown topic requests open this overview.", "Help is local and never opens a browser automatically.",
            [HelpTopicId.Dashboard, HelpTopicId.Settings]),
        Topic(HelpTopicId.Dashboard, "Dashboard", "Summarizes the latest completed scan and offers primary workflow shortcuts.",
            "In-memory summary values from the current session.", "Only the current page selection.",
            "Files, folders, catalog entries, or settings.",
            ["Choose Scan folder.", "Complete a scan.", "Return here for totals or open Results."],
            ["Scan folder", "View results", "Settings"], "Before the first scan, the Dashboard explains how to begin.",
            "If Results is unavailable, complete a scan first.", "Dashboard actions never organize files.",
            [HelpTopicId.ScanFolders, HelpTopicId.Results]),
        Topic(HelpTopicId.ScanFolders, "Scan folders", "Selects local roots for read-only analysis and shows scan progress.",
            "Names, paths, metadata, and supported hashes under explicitly selected roots.", "In-memory scan state and progress only.",
            "Selected files or folders.",
            ["Add one or more accessible folders.", "Start scan.", "Review elapsed time and, once enough comparable work exists, the rounded remaining-time estimate.", "Cancel safely or open Results when complete."],
            ["Browse", "Add folder", "Remove selected", "Start scan", "Cancel scan"], "An empty folder produces a valid empty Results snapshot.",
            "Permission and disappearing-file warnings are isolated and shown safely.", "OpenSorSe does not modify scanned items.",
            [HelpTopicId.Results, HelpTopicId.Diagnostics]),
        Topic(HelpTopicId.Results, "Results", "Searches, filters, sorts, and reviews the immutable current or saved snapshot.",
            "Snapshot metadata, classifications, hashes, planned-operation previews, and local tags.", "In-memory filters and explicitly managed OpenSorSe tags.",
            "File content, names, locations, or timestamps.",
            ["Complete a scan or open a saved snapshot.", "Search or filter.", "Select a row for details.", "Open Duplicate View for grouped exact matches."],
            ["Search", "Filters", "Paging", "Duplicate View", "Tag controls"], "No rows means no snapshot or no rows match current filters.",
            "Clear filters when a known file is not visible.", "Results analysis is read-only; accepted organization suggestions create a Change Plan.",
            [HelpTopicId.DuplicateView, HelpTopicId.AiSuggestions]),
        Topic(HelpTopicId.ReviewChanges, "Review Changes", "Reviews, edits, validates, and explicitly applies a Change Plan.",
            "The selected persisted Change Plan and live metadata needed for validation.", "Approval/edit state, Change Plan persistence, and—only after final confirmation—supported journalled file actions.",
            "Rejected actions, unapproved actions, file contents, or occupied destinations.",
            ["Inspect every action.", "Approve, reject, or edit.", "Validate Plan.", "Review the final summary.", "Explicitly confirm Apply Plan.", "Inspect the result or request Undo."],
            ["Approve all safe", "Deselect all", "Validate Plan", "Apply Plan", "Confirm Apply Plan", "Cancel operation", "Undo"],
            "No plan is normal until a suggestion is accepted.", "Blocking conflicts keep Apply disabled; edit or reject the action and revalidate.",
            "Apply never overwrites. Undo is blocked when restoration could destroy newer data. Filesystems are not perfectly transactional.",
            [HelpTopicId.Results, HelpTopicId.OperationHistory, HelpTopicId.AiSuggestions]),
        Topic(HelpTopicId.DuplicateView, "Duplicates", "Groups files with matching supported SHA-256 hashes and offers an explicitly reviewed safe-removal workflow.",
            "Known members and metadata from the current immutable Results snapshot.", "Selection state and, only after Change Plan review and confirmation, selected-copy recovery moves.",
            "Unselected copies or file contents; it never permanently deletes a duplicate.",
            ["Open Duplicates.", "Select one or more unwanted copies in a group, then move to another group if needed; the selections remain pending.", "Leave at least one keeper in every affected group.", "Choose Review selected duplicates, inspect keepers and removals in the combined Change Plan, then confirm execution.", "Use Undo while conflict checks still pass if a recovery move was mistaken."],
            ["Back to Files", "Show in Files", "Open file", "Open folder", "Review selected duplicates", "Review Changes", "Undo"],
            "No groups means no supported exact hash matches were found.", "Missing files or launch failures are reported per item without breaking the page.",
            "Safe removal moves copies to .opensorse/duplicate-recovery under the scan root. It is journalled and undoable but does not reclaim disk space until that recovery copy is removed separately.", [HelpTopicId.Results, HelpTopicId.ReviewChanges]),
        Topic(HelpTopicId.SavedCatalog, "Saved catalog", "Reviews opt-in bounded historical snapshots stored in OpenSorSe application data.",
            "Saved snapshot metadata, source scope, names, and accepted tags.", "Explicit snapshot names or catalog entries.",
            "Scanned files or folders.",
            ["Enable the catalog.", "Complete a scan.", "Select a saved snapshot.", "Open, name, or explicitly remove it."],
            ["Refresh", "Open selected snapshot", "Save snapshot name", "Remove", "Clear all"], "An empty catalog is normal until an enabled scan completes.",
            "Catalog I/O failures preserve current Results.", "Saved snapshots are historical metadata, not live filesystem state.",
            [HelpTopicId.CatalogSearch, HelpTopicId.CompareSnapshots]),
        Topic(HelpTopicId.CatalogSearch, "Catalog Search", "Searches metadata across saved snapshots without rereading disk.",
            "Saved filenames, paths, extensions, categories, and accepted tags.", "In-memory hits and explicit saved-query definitions.",
            "Files, snapshots, catalog entries, or tags.",
            ["Enter a query and Search.", "Select a hit to open its snapshot.", "Optionally name and save the query.", "Run, rename, or remove saved definitions."],
            ["Search", "Clear query", "Open selected saved snapshot", "Save current query", "Run selected", "Rename", "Remove", "Clear all"],
            "One empty state explains no query, no matches, or no saved definitions.", "Enable catalog storage before searching current saved metadata.",
            "Deleting a saved search deletes only its name and query.", [HelpTopicId.SavedCatalog]),
        Topic(HelpTopicId.CompareSnapshots, "Compare snapshots", "Compares two stored metadata snapshots.",
            "Two explicit saved snapshots and their scope metadata.", "In-memory comparison filters and selection.",
            "Saved snapshots or filesystem state.",
            ["Choose baseline and current snapshots.", "Compare.", "Filter changes.", "Open a selected historical snapshot if needed."],
            ["Baseline", "Current", "Compare", "Filters"], "At least two compatible snapshots are needed.",
            "Scope differences are reported rather than hidden.", "Comparison never verifies or changes stored paths.",
            [HelpTopicId.SavedCatalog, HelpTopicId.AdvancedFeatures]),
        Topic(HelpTopicId.SemanticSearch, "Search", "Hybrid Search finds known files using names, folder names, metadata, document text, OCR, tags, summaries, and related concepts. Results improve as background indexing completes.",
            "Only application-owned local content and Search index data.", "Only rebuildable local Search data and in-memory search results.",
            "Source files; indexing never renames, moves, deletes, or edits them.",
            ["Open Search from primary navigation.", "Enable Search in Settings if it was disabled.", "Build or refresh the existing local index.", "Let background indexing add coverage gradually.", "Enter a natural-language or exact query.", "Review why each result matched.", "Optionally enable AI assistance to rerank only a bounded set of results already found by local Search.", "Pause, resume, retry, maintain, or rebuild when needed."],
            ["Build / refresh index", "Pause", "Resume", "Cancel safely", "Retry failed items", "Prioritize source", "Remove source", "Rebuild", "Maintain storage", "Search", "Open selected result"],
            "An empty index is normal until files have been discovered.", "Interrupted work resumes from durable stage state. Missing files are retained temporarily, and corrupt data requires an explicit backup restore or rebuild.",
            "An empty result is not definitive while coverage is incomplete. Deterministic Search works without Ollama; AI cannot introduce files Search did not find. Review diagnostics before exporting them.", [HelpTopicId.Results, HelpTopicId.Settings, HelpTopicId.AiSetup, HelpTopicId.MediaIntelligence]),
        Topic(HelpTopicId.StructureHistory, "Structure history", "Reviews folder restructuring proposals, applied outcomes, repeat protection, and historical structures.",
            "Bounded relative paths, sizes, timestamps, fingerprints, and application-owned structure history.", "Preview/history records; only an exact separately confirmed proposal may move listed in-root files.",
            "File contents. Diagrams, comparisons, refresh, filters, and preview do not modify files.",
            ["Enter an absolute disposable root.", "Preview restructuring.", "Review source and proposed structures.", "Use Apply only after reviewing every move.", "Capture current structure or inspect past records."],
            ["Preview restructuring", "Propose restructuring again", "Apply reviewed proposal", "Snapshot selector", "Capture current structure", "History filters"],
            "No history is expected until a proposal is created.", "Changed roots, traversal, conflicts, missing sources, reparse destinations, cancellation, and bounds fail closed.",
            "Only successful applies activate repeat protection. Clearing history never changes files but removes that protection record.", [HelpTopicId.AdvancedFeatures, HelpTopicId.OperationHistory]),
        Topic(HelpTopicId.Rules, "Rules", "Reviews deterministic rule data supplied in memory.",
            "Rule names, conditions, and action previews.", "Only in-memory rule state exposed by the current surface.",
            "Files; the 1.1 desktop does not execute raw rule actions directly.", ["Select a rule.", "Review its state and preview information."],
            ["Current rules", "Enable or disable", "Delete"], "No rules is a valid state.",
            "Unsupported or incomplete rule data is reported safely.", "Rule complexity does not grant file mutation authority.", [HelpTopicId.Results]),
        Topic(HelpTopicId.Settings, "Settings", "Controls local file-analysis preferences, optional AI assistance, and other persisted OpenSorSe settings.",
            "The current OpenSorSe settings file.", "Only values explicitly saved to application data.",
            "Scanned files, folders, or external Ollama configuration.",
            ["Choose local file-analysis and indexing options.", "For scanned PDFs or supported images, install Tesseract plus eng/deu language data, enable OCR, and recheck capability.", "Configure optional ffprobe/ffmpeg paths only when audio/video metadata or representative frames are wanted.", "Enable AI assistance only if wanted.", "Review whether the configured AI endpoint is local or remote.", "Discover and select an installed model.", "Save or discard changes."],
            ["Extract searchable content", "Save completed scans in the local library", "Media Intelligence", "Check media capabilities", "Enable AI assistance", "Ollama-compatible endpoint", "Discover models", "Show advanced features", "Save", "Discard changes", "Restore defaults"],
            "Hidden settings remain saved and are not reset.", "Invalid values remain unsaved with an actionable error.",
            "OCR, transcription, representative-frame analysis, and AI-derived descriptions remain off by default. Disabled AI prevents provider communication.", [HelpTopicId.AiSetup, HelpTopicId.MediaIntelligence, HelpTopicId.AdvancedFeatures]),
        Topic(HelpTopicId.Diagnostics, "Diagnostics", "Inspects bounded application events and opt-in AI request diagnostics.",
            "Up to 500 safe session events and, when enabled, 20 redacted session AI requests.", "Filters, selection, clipboard text, or explicit AI diagnostic clearing.",
            "Operation History, scan warnings, user files, or ordinary log files.",
            ["Refresh.", "Filter by severity/category.", "Select and copy safe details.", "Enable advanced AI diagnostics separately when troubleshooting."],
            ["Refresh", "Severity", "Category", "Copy diagnostic details", "Clear AI diagnostics"],
            "No events is a valid early-session state.", "Daily-log write failures do not prevent in-memory diagnostics.",
            "Ordinary details omit raw stacks; AI raw data is opt-in and may contain filenames.", [HelpTopicId.OperationHistory, HelpTopicId.AiSetup]),
        Topic(HelpTopicId.OperationHistory, "Operation History", "Reviews persistent attempted actions, rollback, interruption, and Undo facts.",
            "The bounded local Operation Journal.", "Selection, copied report text, or explicitly confirmed conflict-safe Undo.",
            "File contents, AI prompt bodies, raw responses, or newer conflicting data.",
            ["Refresh history.", "Select an operation.", "Review summary and every action.", "Copy a report if needed.", "Request and confirm Undo only after reviewing conflicts."],
            ["Refresh history", "Copy operation report", "Undo", "Confirm Undo"], "No journal records is normal before the first Apply attempt.",
            "Interrupted, rollback-partial, and Undo-conflict states require action-level review.", "Undo never overwrites and is not a substitute for backups.", [HelpTopicId.ReviewChanges, HelpTopicId.Diagnostics]),
        Topic(HelpTopicId.AiSetup, "AI / Ollama", "Connects optional Ollama-compatible AI and selects an exact installed model; ordinary Search never requires it.",
            "The configured endpoint, provider version/model metadata, and selected settings.", "OpenSorSe settings only after Save.",
            "Ollama installation, models, or user files.",
            ["Enable AI assistance.", "Check whether the endpoint is labelled local or remote.", "Check connection.", "Discover models.", "Select an installed model.", "Set a 5–300 second timeout.", "Enable only the capabilities you need.", "Save."],
            ["Ollama endpoint", "Check connection", "Discover / refresh models", "Installed model", "Request timeout", "Allow local AI to analyze extracted document text"],
            "No discovered models means the provider reported none; OpenSorSe does not download one.", "Unavailable endpoints, models, cancellation, and timeout are reported separately.",
            "No provider check runs while AI is disabled. A non-local endpoint may receive bounded query, metadata, snippet, or extracted-text information supplied to an explicit AI request.", [HelpTopicId.Settings, HelpTopicId.AiSuggestions, HelpTopicId.Privacy]),
        Topic(HelpTopicId.AiSuggestions, "AI suggestions", "Generates narrowly scoped rename, logical folder, or document-text interpretation proposals for review.",
            "Exact filenames and bounded metadata; extracted native/OCR text only when its separate switch is enabled and the user explicitly requests interpretation.", "Only in-memory proposals and optional local review decisions.",
            "Source files and folders. AI output never changes them automatically.",
            ["Select eligible Results context.", "Generate one explicit request.", "Observe progress.", "Review the unverified validated proposal.", "Accept a rename/folder proposal to create a Change Plan, or reject/dismiss/cancel."],
            ["Generate", "Interpret extracted text", "Cancel AI request", "Create Change Plan", "Reject", "Dismiss"],
            "No suggestion or no extracted text is a valid outcome.", "Unsafe, malformed, unknown-identity, duplicate, incomplete, or oversized responses are rejected as a whole.",
            "OCR text can be inaccurate. AI output is untrusted and never automatically reaches a file operation.", [HelpTopicId.Results, HelpTopicId.AiSetup]),
        Topic(HelpTopicId.WatchedFolders, "Watched Folders", "Keeps explicitly registered folders observed and proposes reviewed updates when relevant changes occur.",
            "Metadata and events within each configured watched-folder boundary.", "Application-owned watched-folder state and proposals; files move only through a separately confirmed Change Plan.",
            "Original files during observation, source ownership, or unrelated folders.",
            ["Add an absolute folder.", "Choose an indexing level and workflow where needed.", "Review activity and failures.", "Open each proposed Change Plan before applying it.", "Pause, resume, or remove the source explicitly."],
            ["Add watched folder", "Pause", "Resume", "Review plan", "Activity", "Remove"],
            "An empty list means no folder is being watched.", "Unavailable paths and permission failures remain isolated and retryable where safe.",
            "Watcher events never bypass Change Plan review and self-generated operations are reconciled to avoid loops.", [HelpTopicId.Workflows, HelpTopicId.ReviewChanges, HelpTopicId.Diagnostics]),
        Topic(HelpTopicId.Workflows, "Workflows", "Stores reusable scan profiles and sorting recipes without bypassing review.",
            "Application-owned workflow definitions and explicit user inputs.", "Workflow definitions, revisions, assignments, and reviewable plan proposals.",
            "Files until a generated Change Plan is separately reviewed and confirmed.",
            ["Choose or create a profile.", "Review enabled capabilities and recipe values.", "Save a revision.", "Run it manually or assign it to a watched folder.", "Review every resulting Change Plan."],
            ["New profile", "Save revision", "Run scan", "Assign to watched folder", "Import", "Export", "Archive"],
            "Built-in profiles remain available when no user profiles exist.", "Invalid imports and unresolved recipe fields fail without changing files.",
            "AI-enabled workflow steps remain optional and cannot execute file changes directly.", [HelpTopicId.WatchedFolders, HelpTopicId.ReviewChanges]),
        Topic(HelpTopicId.RelatedFiles, "Related Files", "Discovers explainable connections between the selected file and other indexed files.",
            "Bounded indexed evidence, relationship records, manual decisions, and projection status.", "Virtual relationship/collection records and explicit manual decisions.",
            "Original files; Related Files and Smart Collections are virtual.",
            ["Open the single Related Files destination from primary navigation.", "Let indexing build applicable evidence.", "Select a file.", "Inspect evidence for each connection.", "Confirm, reject, forget, or rebuild only when needed.", "Open Collections separately for saved or virtual grouped sets."],
            ["Refresh view", "File", "Evidence", "Confirm", "Reject", "Forget", "Rebuild"],
            "No connections is valid when evidence is insufficient or indexing is incomplete.", "Unavailable dependencies reduce coverage rather than inventing evidence.",
            "Every displayed connection is derived from stored evidence. Related Files is not duplicated under Collections; advanced architecture documentation calls the underlying projection the Knowledge Graph.", [HelpTopicId.SemanticSearch, HelpTopicId.Privacy]),
        Topic(HelpTopicId.Privacy, "Privacy", "Explains what local indexing and optional AI can retain or transmit.",
            "Only the settings and bounded index categories needed to explain current privacy state.", "Explicit exclusions, retention choices, and index-only forget actions.",
            "Original files; forgetting index data never deletes source files.",
            ["Remember that scanning, indexing, extraction, and derived Search storage are local by default.", "Inspect stored data for a file or source.", "Exclude sensitive folders or types when needed.", "Treat every non-loopback AI endpoint as remote.", "Review diagnostic exports before sharing."],
            ["Indexing level", "Exclusions", "Inspect indexed data", "Forget", "AI endpoint", "Diagnostics export"],
            "No generated content is stored when the corresponding processing option is disabled.", "Search and indexing continue locally when Ollama is unavailable.",
            "OpenSorSe has no telemetry or cloud-indexing dependency. A configured remote Ollama-compatible endpoint is outside that local boundary and may receive only the information supplied to an explicitly enabled AI request.", [HelpTopicId.Settings, HelpTopicId.AiSetup, HelpTopicId.MediaIntelligence, HelpTopicId.Diagnostics]),
        Topic(HelpTopicId.MediaIntelligence, "Media Intelligence", "Makes supported images, audio, and video searchable through the same local Search experience.",
            "Bounded image headers and EXIF, local OCR output, and metadata returned by explicitly available local media tools. This v2.2 candidate includes no concrete transcription or visual-description provider.",
            "Application-owned local index records and bounded preview-cache files.",
            "Original images, recordings, videos, embedded metadata, or media contents.",
            ["Enable only the media categories you need in Settings.", "Check capability availability before enabling optional work.", "Configure only reviewed local ffprobe, ffmpeg, or Tesseract executables; OpenSorSe does not download them.", "Let background indexing process supported media within the configured limits.", "Search normally and inspect the evidence label.", "Use indexed-data inspection or clear controls to remove derived media evidence without deleting the source file."],
            ["Image metadata", "Image OCR", "Audio/video metadata", "Transcription", "Representative frames", "Visual descriptions", "Check media capabilities", "Resource limits"],
            "Transcription and visual descriptions are unavailable in this candidate; frame analysis and OCR are unavailable until their optional local tools are configured. Filename and ordinary indexed Search still work.",
            "Corrupt files, unsupported codecs, timeouts, and disappearing files fail per item. Check Advanced Diagnostics for provider and bound details.",
            "OCR, transcripts, GPS, and descriptions may reveal sensitive facts not visible in a filename. Processing is local by default; no telemetry, facial recognition, person identification, reverse geocoding, or silent upload is used.",
            [HelpTopicId.SemanticSearch, HelpTopicId.Settings, HelpTopicId.Privacy, HelpTopicId.Diagnostics]),
        Topic(HelpTopicId.Troubleshooting, "Troubleshooting", "Provides safe recovery steps for scanning, Search, AI, OCR, and file-operation failures.",
            "User-safe status, notifications, Advanced Diagnostics, and Operation History.", "Only explicit retry, repair, rebuild, or dismissal state.",
            "Original files unless the user separately confirms a valid Change Plan.",
            ["Read the page status.", "Open the notification badge for recent messages.", "Inspect Advanced Diagnostics for durable evidence.", "Check permissions or optional dependencies.", "Retry the smallest failed operation.", "Use targeted repair before a full rebuild."],
            ["Notifications", "Advanced Diagnostics", "Retry", "Repair", "Rebuild", "Operation History"],
            "No notification means there is no current transient message; diagnostic evidence may still exist.", "Do not repeatedly retry a deterministic permission, schema, or destination conflict without correcting its cause.",
            "Dismissed notifications do not erase diagnostics. Copy reports only after reviewing them for private paths or content.", [HelpTopicId.Diagnostics, HelpTopicId.OperationHistory, HelpTopicId.Privacy]),
        Topic(HelpTopicId.AdvancedFeatures, "Advanced features", "Reveals specialist comparison, diagnostics, history, and troubleshooting controls.",
            "Existing saved settings and advanced page data.", "Only interface visibility after Save.",
            "Hidden values or user files.",
            ["Enable Show advanced features.", "Save.", "Use only the specialist pages needed.", "Disable and save to simplify the interface."],
            ["Show advanced features"], "Hidden pages safely return to Dashboard.",
            "A hidden page cannot be reached through stale navigation.", "Critical safety messages remain visible in regular mode.", [HelpTopicId.Settings, HelpTopicId.Diagnostics]),
        Topic(HelpTopicId.About, "About", "Shows product identity, version, license, and documentation addresses.",
            "Static assembly and repository metadata.", "Nothing.",
            "Files, settings, network state, or clipboard unless the user copies text.",
            ["Review version and license.", "Copy a repository or documentation address if needed."],
            ["Repository address", "Documentation address"], "About always has static content.",
            "Addresses are shown as copyable text; no browser is opened automatically.", "About is read-only.", [HelpTopicId.HelpOverview]),
    ]);

    /// <summary>Gets all topics in stable display order.</summary>
    public static IReadOnlyList<HelpTopic> Topics => TopicsValue;

    /// <summary>Gets a registered topic or the overview fallback.</summary>
    public static HelpTopic Get(HelpTopicId topicId) =>
        TopicsValue.FirstOrDefault(topic => topic.Id == topicId) ?? TopicsValue[0];

    private static HelpTopic Topic(
        HelpTopicId id,
        string title,
        string purpose,
        string reads,
        string changes,
        string doesNotChange,
        IReadOnlyList<string> workflow,
        IReadOnlyList<string> controls,
        string emptyStates,
        string commonErrors,
        string safety,
        IReadOnlyList<HelpTopicId> related) =>
        new(id, title, purpose, reads, changes, doesNotChange, workflow, controls, emptyStates, commonErrors, safety, related);
}
