<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <OmniSorSeVersion Condition="'$(OmniSorSeVersion)' == ''">2.10.0-rc</OmniSorSeVersion>
    <OmniSorSeFileVersion Condition="'$(OmniSorSeFileVersion)' == ''">2.10.0.0</OmniSorSeFileVersion>
    <SourceRevisionId Condition="'$(SourceRevisionId)' == ''">unversioned</SourceRevisionId>
    <Version>$(OmniSorSeVersion)</Version>
    <AssemblyVersion>$(OmniSorSeFileVersion)</AssemblyVersion>
    <FileVersion>$(OmniSorSeFileVersion)</FileVersion>
    <InformationalVersion>$(OmniSorSeVersion)+$(SourceRevisionId)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="SourceRevision" Value="$(SourceRevisionId)" />
    <AssemblyMetadata Include="BuildConfiguration" Value="$(Configuration)" />
  </ItemGroup>
</Project>
