<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OmniSorSe.Screenshots</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/OpenSorSe.Desktop/OpenSorSe.Desktop.csproj" />
    <Content Include="fixtures/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
